name: subpub
description: A lightweight and efficient state management solution for Flutter implementing the publisher-subscriber pattern with automatic dependency tracking and macro-powered code generation
version: 0.0.1
homepage: https://github.com/p4-k4/subpub
repository: https://github.com/p4-k4/subpub
issue_tracker: https://github.com/p4-k4/subpub/issues
documentation: https://github.com/p4-k4/subpub#readme
license: MIT
topics:
  - "flutter"
  - "state-management"
  - "publisher-subscriber"
  - "dependency-tracking"
  - "dart-macros"

environment:
  sdk: ^3.5.0-152
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  macros: 0.1.3-main.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
